package com.project.jingdong.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.project.jingdong.bean.HistorySearchBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_SEARCH_BEAN".
*/
public class HistorySearchBeanDao extends AbstractDao<HistorySearchBean, Void> {

    public static final String TABLENAME = "HISTORY_SEARCH_BEAN";

    /**
     * Properties of entity HistorySearchBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SearchName = new Property(0, String.class, "searchName", false, "SEARCH_NAME");
    }


    public HistorySearchBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HistorySearchBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_SEARCH_BEAN\" (" + //
                "\"SEARCH_NAME\" TEXT);"); // 0: searchName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_SEARCH_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistorySearchBean entity) {
        stmt.clearBindings();
 
        String searchName = entity.getSearchName();
        if (searchName != null) {
            stmt.bindString(1, searchName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistorySearchBean entity) {
        stmt.clearBindings();
 
        String searchName = entity.getSearchName();
        if (searchName != null) {
            stmt.bindString(1, searchName);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public HistorySearchBean readEntity(Cursor cursor, int offset) {
        HistorySearchBean entity = new HistorySearchBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // searchName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistorySearchBean entity, int offset) {
        entity.setSearchName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(HistorySearchBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(HistorySearchBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(HistorySearchBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
